# This file is licensed under the 0BSD License: https://opensource.org/license/0bsd

services:
  vaultwarden:
    container_name: quollix_vaultwarden_vaultwarden
    image: vaultwarden/server:1.37.3-alpine@sha256:9a905c5cf5df61bb827da3805e160170741c0b53b0c63bb07e1afd3d2e21b1c8
    environment:
      ADMIN_TOKEN: "${SECRET_ADMIN_TOKEN}"
      SIGNUPS_ALLOWED: false
      DOMAIN: https://vaultwarden.${BASE_DOMAIN}

      SSO_ENABLED: true
      SSO_AUTHORITY: https://quollix.${BASE_DOMAIN}
      SSO_CLIENT_ID: ${CLIENT_ID}
      SSO_CLIENT_SECRET: ${CLIENT_SECRET}
      SSO_ONLY: true
      SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION: true
    volumes:
      - quollix_vaultwarden_data:/data
    labels:
      quollix.port: 80

volumes:
  quollix_vaultwarden_data: null
